# fly.toml app configuration file generated for game-api on 2023-09-19T14:47:01-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "game-api"
primary_region = "gru"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
