version: '3.5'
services: 
    server:
        build: ../application
        container_name: "fastapi"
        #todo fix 2way bind folder
        volumes:
            - type: bind
              source: ./application
              target: /application
              read_only: true
        ports:
            - 8080:8080


#docker-compose -f fastapi.yml up